name: Fetch Strava Data and Deploy

on:
  schedule:
    - cron: '0 */2 * * *'  # Ogni 2 ore invece di 20 minuti
  workflow_dispatch:

# Aggiungi questi permessi espliciti
permissions:
  contents: write  # Permette di scrivere nel repository (commit/push)
  pages: write     # Permette di gestire GitHub Pages
  id-token: write  # Necessario per il deployment

jobs:
  fetch_data_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: Fetch Strava activities
        run: node fetch-strava-activities.js
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          BEST_EFFORTS_LIMIT: 6
          ZONES_LIMIT: 6
          SWIM_PACE_LIMIT: 4

      - name: Show latest JSON date
        run: |
          node -e "const d=require('./public/strava-data.json'); console.log('Latest date in strava-data.json:', d?.[d.length-1]?.date, 'Total points:', d?.length);"

      - name: Commit and push if data changed
        id: commit
        run: |
          set -e
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/strava-data.json public/strava-aggregates.json public/athlete-stats.json public/best-efforts.json public/zones-summary.json public/swim-paces.json || true
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Update Strava data"
            git push
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to Strava data."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build project
        if: steps.commit.outputs.changed == 'true'
        run: npm run build

      - name: Deploy to GitHub Pages
        if: steps.commit.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
